<?php
session_start();
require __DIR__ . '/db.php';
global $config;
$page = $_GET['page'] ?? 'home';

function layout_start(string $title): void { global $config; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> | UPL</title><link rel="stylesheet" href="/static/style.css"></head><body>
<nav class="nav"><a class="brand" href="/"><img src="/static/upl-logo.png" alt="UPL Logo"><b>UPL</b></a><div class="links"><a href="/">HOME</a><a href="/?page=registration">REGISTRATION</a><a href="/?page=team-registration">TEAM REGISTRATION</a><a href="/?page=teams">TEAMS</a><a href="/?page=players">PLAYERS</a><a href="/?page=fixtures">FIXTURES</a><a href="/?page=points-table">POINTS TABLE</a><a href="/?page=news">NEWS</a><a href="/?page=gallery">GALLERY</a></div></nav>
<?php }
function layout_end(): void { ?><footer><span>© UPL • Uttar Lakshmipur Premier League</span><span>Venue: Uttar Lakshmipur High School</span></footer></body></html><?php }

if ($page === 'health') { header('Content-Type: application/json'); echo json_encode(['status'=>'ok','service'=>'UPL Website']); exit; }

// ---------------- Admin actions ----------------
if ($_SERVER['REQUEST_METHOD']==='POST') {
    if ($page==='admin-login') {
        $u=trim($_POST['username']??''); $p=$_POST['password']??'';
        $s=db()->prepare('SELECT * FROM admins WHERE username=? LIMIT 1'); $s->execute([$u]); $a=$s->fetch();
        if ($a && password_verify($p,$a['password_hash'])) { $_SESSION['admin']=true; $_SESSION['admin_user']=$u; redirect_to('/?page=admin'); }
        $login_error='Invalid username or password.';
    }
    if (str_starts_with($page,'admin-')) {
        require_admin(); $pdo=db();
        try {
            if ($page==='admin-player-status') { $s=$pdo->prepare('UPDATE players SET status=? WHERE id=?'); $s->execute([$_POST['status']??'Pending',(int)$_POST['id']]); }
            elseif ($page==='admin-player-delete') { $s=$pdo->prepare('DELETE FROM players WHERE id=?'); $s->execute([(int)$_POST['id']]); }
            elseif ($page==='admin-team-delete') { $s=$pdo->prepare('DELETE FROM teams WHERE id=?'); $s->execute([(int)$_POST['id']]); }
            elseif ($page==='admin-team-status') { $s=$pdo->prepare('UPDATE team_interest SET status=? WHERE id=?'); $s->execute([$_POST['status']??'Interested',(int)$_POST['id']]); }
            elseif ($page==='admin-team-interest-delete') { $s=$pdo->prepare('DELETE FROM team_interest WHERE id=?'); $s->execute([(int)$_POST['id']]); }
            elseif ($page==='admin-team-add') { $name=trim($_POST['name']??''); if($name){$s=$pdo->prepare('INSERT IGNORE INTO teams(name,description) VALUES(?,?)');$s->execute([$name,trim($_POST['description']??'')]);} }
            elseif ($page==='admin-fixture-add') { $s=$pdo->prepare('INSERT INTO fixtures(match_no,team1,team2,match_date,match_time,venue,status,result_text) VALUES(?,?,?,?,?,?,?,?)'); $s->execute([$_POST['match_no']?:null,trim($_POST['team1']??''),trim($_POST['team2']??''),$_POST['date']?:null,$_POST['time']?:null,$_POST['venue']?:'Uttar Lakshmipur High School',$_POST['status']?:'Upcoming',trim($_POST['result']??'')]); }
            elseif ($page==='admin-fixture-delete') { $s=$pdo->prepare('DELETE FROM fixtures WHERE id=?');$s->execute([(int)$_POST['id']]); }
            elseif ($page==='admin-news-add') { $s=$pdo->prepare('INSERT INTO news(title,body,published) VALUES(?,?,1)');$s->execute([trim($_POST['title']??''),trim($_POST['body']??'')]); }
            elseif ($page==='admin-news-delete') { $s=$pdo->prepare('DELETE FROM news WHERE id=?');$s->execute([(int)$_POST['id']]); }
            elseif ($page==='admin-points-add') { $s=$pdo->prepare('INSERT INTO points_table(team_name,group_name,played,won,lost,tied,points,nrr) VALUES(?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE group_name=VALUES(group_name),played=VALUES(played),won=VALUES(won),lost=VALUES(lost),tied=VALUES(tied),points=VALUES(points),nrr=VALUES(nrr)');$s->execute([trim($_POST['team_name']??''),strtoupper($_POST['group_name']??'A'),(int)($_POST['played']??0),(int)($_POST['won']??0),(int)($_POST['lost']??0),(int)($_POST['tied']??0),(int)($_POST['points']??0),(float)($_POST['nrr']??0)]); }
            elseif ($page==='admin-points-delete') { $s=$pdo->prepare('DELETE FROM points_table WHERE id=?');$s->execute([(int)$_POST['id']]); }
            elseif ($page==='admin-gallery-delete') { $s=$pdo->prepare('DELETE FROM gallery WHERE id=?');$s->execute([(int)$_POST['id']]); }
        } catch(Throwable $e) { $admin_error=$e->getMessage(); }
        redirect_to('/?page=admin');
    }
}
if ($page==='logout') { session_destroy(); redirect_to('/'); }

// ---------------- Public pages ----------------
if ($page==='home') {
    $pdo=db(); $fixtures=$pdo->query('SELECT * FROM fixtures ORDER BY match_date,match_time LIMIT 3')->fetchAll(); $news=$pdo->query('SELECT * FROM news WHERE published=1 ORDER BY id DESC LIMIT 3')->fetchAll();
    layout_start('Uttar Lakshmipur Premier League'); ?>
<header class="hero"><div><img src="/static/upl-logo.png" alt="UPL Logo"><div class="date">Uttar Lakshmipur Premier League</div><h1>The Battle <span>Begins</span></h1><p>Player registration opens in September • Matches in October & November</p><a class="btn" href="/?page=registration">PLAYER REGISTRATION</a><a class="btn alt" href="/?page=team-registration">TEAM REGISTRATION</a></div></header>
<section class="wrap"><div class="section-head"><div><h2>UPL</h2><p>Passion • Pride • Cricket • One League</p></div></div><div class="quick"><a class="card" href="/?page=registration"><strong>Registration</strong><span class="muted">Register as a player</span></a><a class="card" href="/?page=team-registration"><strong>Team Registration</strong><span class="muted">Register your team</span></a><a class="card" href="/?page=teams"><strong>Teams</strong><span class="muted">Team information</span></a><a class="card" href="/?page=players"><strong>Players</strong><span class="muted">Approved players</span></a></div></section>
<section class="wrap"><div class="section-head"><div><h2>Upcoming Matches</h2><p>Fixture schedule will be updated here.</p></div></div><div class="grid3"><?php if($fixtures): foreach($fixtures as $f): ?><div class="card match"><div class="date">Match <?=e($f['match_no']?:'TBA')?> • <?=e($f['status'])?></div><div class="teams"><div class="team"><?=e($f['team1'])?></div><div class="vs">VS</div><div class="team"><?=e($f['team2'])?></div></div><div class="muted"><?=e($f['match_date']?:'Date TBA')?> • <?=e($f['match_time']?:'Time TBA')?><br><?=e($f['venue'])?></div></div><?php endforeach; else: ?><div class="card"><div class="date">COMING SOON</div><h3>Fixtures will be announced</h3><p class="muted">UPL matches are planned for October and November.</p></div><?php endif; ?></div></section>
<section class="wrap"><div class="section-head"><div><h2>Latest Announcements</h2><p>Official UPL updates.</p></div></div><div class="news"><?php if($news): foreach($news as $n): ?><article class="card"><div class="date">UPL</div><h3><?=e($n['title'])?></h3><p><?=nl2br(e($n['body']))?></p></article><?php endforeach; else: ?><article class="card"><div class="date">COMING SOON</div><h3>Very soon, the game begins.</h3><p>Player registration will open in September. Matches are planned for October and November.</p></article><?php endif; ?></div></section>
<section class="wrap"><div class="banner"><div class="date">VENUE</div><h2>Uttar Lakshmipur High School</h2><p class="muted">Prize details and tournament rules will be announced later.</p><a class="btn" href="https://www.facebook.com/share/1H6PF4UPKz/" target="_blank">Follow UPL on Facebook</a></div></section><?php layout_end(); exit; }

if ($page==='registration') {
    layout_start('Player Registration'); ?>
<header class="hero" style="min-height:auto;padding:45px 20px"><div><img src="/static/upl-logo.png" style="width:min(210px,55vw)" alt="UPL"><h1>Player <span>Registration</span></h1><p>Registration form</p></div></header><main class="wrap"><div class="card"><form class="grid" method="post" action="/?page=player-submit" enctype="multipart/form-data"><div><label>Full Name *</label><input name="name" required></div><div><label>Age *</label><input name="age" type="number" min="10" max="80" required></div><div><label>Phone / WhatsApp *</label><input name="phone" pattern="[0-9]{10}" inputmode="numeric" required></div><div><label>E-mail *</label><input name="email" type="email" required></div><div><label>Village Name *</label><input name="village" required></div><div><label>Gram Panchayat *</label><select name="panchayat" required><option value="">Select</option><?php foreach(['Uttar Laxmipur','Mothabari','Uttar Panchanandapur-I','Uttar Panchanandapur-II','Gangaprasad','Bangitola','Rathbari','Hamidpur','Rajnagar'] as $p): ?><option><?=e($p)?></option><?php endforeach; ?></select></div><div><label>Primary Role *</label><select name="role" required><option value="">Select</option><option>Batter</option><option>Bowler</option><option>All-Rounder</option></select></div><div><label>Batting Style</label><select name="batting"><option value="">Select</option><option>Right-hand Batsman</option><option>Left-hand Batsman</option></select></div><div><label>Bowling Style</label><select name="bowling"><option value="">Select</option><option>Right-hand Bowling</option><option>Left-hand Bowling</option></select></div><div><label>Player Photo *</label><input name="photo" type="file" accept=".jpg,.jpeg,.png,.webp" required></div><div class="full"><button class="btn" type="submit">SUBMIT REGISTRATION</button><p class="muted">Payment integration will be connected before production launch.</p></div></form></div></main><?php layout_end(); exit; }

if ($page==='player-submit' && $_SERVER['REQUEST_METHOD']==='POST') {
    $pdo=db(); $phone=preg_replace('/\D/','',$_POST['phone']??''); $email=trim($_POST['email']??''); $photo=upload_image($_FILES['photo']??[],'players');
    if(strlen($phone)!==10 || !$photo) { layout_start('Registration Error'); echo '<main class="wrap"><div class="banner">Please provide a valid 10-digit phone number and JPG/PNG/WEBP photo.</div></main>'; layout_end(); exit; }
    try { $no=next_no('UPL26-','players','registration_no'); $s=$pdo->prepare('INSERT INTO players(registration_no,full_name,age,phone,email,village,gram_panchayat,primary_role,batting_style,bowling_style,photo_path,payment_status,paid_amount,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$no,trim($_POST['name']),intval($_POST['age']),$phone,$email,trim($_POST['village']),trim($_POST['panchayat']),trim($_POST['role']),trim($_POST['batting']??''),trim($_POST['bowling']??''),$photo,'Pending',0,'Pending']); layout_start('Registration Submitted'); echo '<main class="wrap"><div class="banner"><h2>Registration submitted</h2><p>Your Registration No: <strong>'.e($no).'</strong></p><p>Admin will verify the application.</p><a class="btn" href="/">BACK HOME</a></div></main>'; layout_end(); } catch(Throwable $e) { layout_start('Registration Error'); echo '<main class="wrap"><div class="banner">This phone or email may already be registered.</div></main>'; layout_end(); } exit; }

if ($page==='team-registration') { layout_start('Team Registration'); ?><header class="hero" style="min-height:auto;padding:45px 20px"><div><img src="/static/upl-logo.png" style="width:min(210px,55vw)" alt="UPL"><h1>Team <span>Registration</span></h1><p>Show your interest in participating in UPL.</p></div></header><main class="wrap"><div class="card"><p><strong>Team Registration Fee: ₹5,000</strong><br><span class="muted">The ₹5,000 registration fee is NOT being collected now.</span></p><p><strong>Interest/Application Charge: ₹100</strong><br><span class="muted">Pay ₹100 by the UPI QR code supplied by the UPL committee, then upload the successful payment screenshot.</span></p></div><section class="card" style="margin-top:20px;text-align:center"><h2>PAY ₹100 BY QR CODE</h2><img src="/static/team-payment-qr.png" style="width:min(360px,82vw);border-radius:12px;background:#fff;padding:8px" alt="Payment QR"><p><strong>Scan and pay exactly ₹100.</strong></p></section><section class="card"><form class="grid" method="post" action="/?page=team-submit" enctype="multipart/form-data"><div><label>Team Name *</label><input name="team_name" required></div><div><label>Contact Person *</label><input name="contact_name" required></div><div><label>Phone / WhatsApp *</label><input name="phone" pattern="[0-9]{10}" required></div><div><label>E-mail *</label><input name="email" type="email" required></div><div><label>Village Name *</label><input name="village" required></div><div><label>Gram Panchayat *</label><select name="panchayat" required><option value="">Select</option><?php foreach(['Uttar Laxmipur','Mothabari','Uttar Panchanandapur-I','Uttar Panchanandapur-II','Gangaprasad','Bangitola','Rathbari','Hamidpur','Rajnagar'] as $p): ?><option><?=e($p)?></option><?php endforeach; ?></select></div><div class="full"><label>Payment Screenshot *</label><input name="payment_screenshot" type="file" accept=".jpg,.jpeg,.png" required></div><div class="full"><button class="btn" type="submit">SUBMIT TEAM APPLICATION</button></div></form></section></main><?php layout_end(); exit; }

if ($page==='team-submit' && $_SERVER['REQUEST_METHOD']==='POST') { $pdo=db(); $shot=upload_image($_FILES['payment_screenshot']??[],'team-payments'); if(!$shot){layout_start('Team Registration Error');echo '<main class="wrap"><div class="banner">Please upload a JPG or PNG payment screenshot.</div></main>';layout_end();exit;} try{$no=next_no('UPL-26-TI-','team_interest','interest_no');$s=$pdo->prepare('INSERT INTO team_interest(interest_no,team_name,contact_name,phone,email,village,gram_panchayat,registration_fee,interest_charge,payment_status,status,paid_amount,payment_screenshot_url) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$no,trim($_POST['team_name']),trim($_POST['contact_name']),preg_replace('/\D/','',$_POST['phone']),trim($_POST['email']),trim($_POST['village']),trim($_POST['panchayat']),5000,100,'Submitted','Interested',100,$shot]);layout_start('Team Application Submitted');echo '<main class="wrap"><div class="banner"><h2>Team application submitted</h2><p>Application No: <strong>'.e($no).'</strong></p><p>The committee will manually verify the payment.</p></div></main>';layout_end();}catch(Throwable $e){layout_start('Error');echo '<main class="wrap"><div class="banner">Unable to submit. Please check your details.</div></main>';layout_end();}exit; }

if (in_array($page,['teams','players','fixtures','points-table','news','gallery'],true)) {
    $pdo=db(); $titles=['teams'=>'Teams','players'=>'Approved Players','fixtures'=>'Fixtures','points-table'=>'Points Table','news'=>'News','gallery'=>'Gallery']; layout_start($titles[$page]); echo '<main class="wrap">';
    if($page==='teams'){ $rows=$pdo->query('SELECT * FROM teams ORDER BY name')->fetchAll(); echo '<div class="grid3">';foreach($rows as $r)echo '<div class="card"><h3>'.e($r['name']).'</h3><p class="muted">'.nl2br(e($r['description']??'' )).'</p></div>';echo '</div>'; }
    elseif($page==='players'){ $rows=$pdo->query("SELECT * FROM players WHERE status='Approved' ORDER BY full_name")->fetchAll(); echo '<div class="grid3">';foreach($rows as $r)echo '<div class="card"><h3>'.e($r['full_name']).'</h3><p class="muted">'.e($r['primary_role']).' • '.e($r['village']).'</p></div>';echo '</div>'; }
    elseif($page==='fixtures'){ $rows=$pdo->query('SELECT * FROM fixtures ORDER BY match_date,match_time')->fetchAll();echo '<div class="grid3">';foreach($rows as $r)echo '<div class="card match"><div class="date">'.e($r['status']).'</div><div class="teams"><div class="team">'.e($r['team1']).'</div><div class="vs">VS</div><div class="team">'.e($r['team2']).'</div></div><p class="muted">'.e($r['match_date']).' • '.e($r['match_time']).'<br>'.e($r['venue']).'</p></div>';echo '</div>'; }
    elseif($page==='points-table'){ $rows=$pdo->query('SELECT * FROM points_table ORDER BY group_name,points DESC,nrr DESC,team_name')->fetchAll();echo '<table class="table"><tr><th>TEAM</th><th>GROUP</th><th>P</th><th>W</th><th>L</th><th>PTS</th><th>NRR</th></tr>';foreach($rows as $r)echo '<tr><td>'.e($r['team_name']).'</td><td>'.e($r['group_name']).'</td><td>'.$r['played'].'</td><td>'.$r['won'].'</td><td>'.$r['lost'].'</td><td>'.$r['points'].'</td><td>'.$r['nrr'].'</td></tr>';echo '</table>'; }
    elseif($page==='news'){ $rows=$pdo->query('SELECT * FROM news WHERE published=1 ORDER BY id DESC')->fetchAll();echo '<div class="news">';foreach($rows as $r)echo '<article class="card"><div class="date">UPL</div><h3>'.e($r['title']).'</h3><p>'.nl2br(e($r['body'])).'</p></article>';echo '</div>'; }
    else { $rows=$pdo->query('SELECT * FROM gallery ORDER BY id DESC')->fetchAll();echo '<div class="grid3">';foreach($rows as $r)echo '<div class="card"><img src="'.e($r['image_path']).'" alt="'.e($r['title']).'" style="width:100%;border-radius:10px"><h3>'.e($r['title']).'</h3></div>';echo '</div>'; }
    echo '</main>'; layout_end(); exit;
}

if ($page==='admin-login') { layout_start('Admin Login'); ?><main class="wrap"><div class="card" style="max-width:520px;margin:auto"><h2>ADMIN LOGIN</h2><?php if(!empty($login_error))echo '<p class="muted">'.e($login_error).'</p>'; ?><form method="post" action="/?page=admin-login"><label>Username</label><input name="username" required><label style="display:block;margin-top:12px">Password</label><input type="password" name="password" required style="margin-bottom:15px"><button class="btn">LOGIN</button></form></div></main><?php layout_end(); exit; }

if ($page==='admin') { require_admin(); $pdo=db(); $players=$pdo->query('SELECT * FROM players ORDER BY id DESC')->fetchAll();$teams=$pdo->query('SELECT * FROM teams ORDER BY name')->fetchAll();$apps=$pdo->query('SELECT * FROM team_interest ORDER BY id DESC')->fetchAll();$fixtures=$pdo->query('SELECT * FROM fixtures ORDER BY match_date,match_time')->fetchAll();$news=$pdo->query('SELECT * FROM news ORDER BY id DESC')->fetchAll();$points=$pdo->query('SELECT * FROM points_table ORDER BY group_name,points DESC,nrr DESC')->fetchAll();$gallery=$pdo->query('SELECT * FROM gallery ORDER BY id DESC')->fetchAll(); layout_start('Admin Panel'); ?><main class="wrap"><div class="section-head"><div><h2>ADMIN PANEL</h2><p>Logged in as <?=e($_SESSION['admin_user']??'admin')?></p></div><a class="btn alt" href="/?page=logout">LOGOUT</a></div>
<div class="card"><h3>Player Registrations</h3><table class="table"><tr><th>NAME</th><th>PHONE</th><th>ROLE</th><th>STATUS</th><th>ACTION</th></tr><?php foreach($players as $r): ?><tr><td><?=e($r['full_name'])?></td><td><?=e($r['phone'])?></td><td><?=e($r['primary_role'])?></td><td><?=e($r['status'])?></td><td><form style="display:inline" method="post" action="/?page=admin-player-status"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status"><option>Pending</option><option>Approved</option><option>Rejected</option></select><button class="btn small">SAVE</button></form><form style="display:inline" method="post" action="/?page=admin-player-delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn small danger" onclick="return confirm('Delete this player?')">DELETE</button></form></td></tr><?php endforeach;?></table></div>
<div class="card" style="margin-top:20px"><h3>Team Applications</h3><table class="table"><tr><th>TEAM</th><th>CONTACT</th><th>PHONE</th><th>STATUS</th><th>ACTION</th></tr><?php foreach($apps as $r): ?><tr><td><?=e($r['team_name'])?></td><td><?=e($r['contact_name'])?></td><td><?=e($r['phone'])?></td><td><?=e($r['status'])?></td><td><form style="display:inline" method="post" action="/?page=admin-team-status"><input type="hidden" name="id" value="<?=$r['id']?>"><select name="status"><option>Interested</option><option>Contacted</option><option>Approved</option><option>Rejected</option></select><button class="btn small">SAVE</button></form><form style="display:inline" method="post" action="/?page=admin-team-interest-delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn small danger" onclick="return confirm('Delete this team application?')">DELETE</button></form></td></tr><?php endforeach;?></table></div>
<div class="grid3" style="margin-top:20px"><div class="card"><h3>Add Team</h3><form method="post" action="/?page=admin-team-add"><input name="name" placeholder="Team name" required><textarea name="description" placeholder="Description"></textarea><button class="btn">ADD</button></form></div><div class="card"><h3>Add Fixture</h3><form method="post" action="/?page=admin-fixture-add"><input name="match_no" placeholder="Match no"><input name="team1" placeholder="Team 1" required><input name="team2" placeholder="Team 2" required><input name="date" type="date"><input name="time" placeholder="Time"><input name="venue" placeholder="Venue"><button class="btn">ADD</button></form></div><div class="card"><h3>Add News</h3><form method="post" action="/?page=admin-news-add"><input name="title" placeholder="Title" required><textarea name="body" placeholder="News" required></textarea><button class="btn">ADD</button></form></div></div>
<div class="card" style="margin-top:20px"><h3>Existing Teams</h3><?php foreach($teams as $r): ?><span class="btn alt" style="margin:4px"><?=e($r['name'])?></span><?php endforeach;?></div>
</main><?php layout_end(); exit; }

layout_start('Page not found'); echo '<main class="wrap"><div class="banner"><h2>Page not found</h2><a class="btn" href="/">HOME</a></div></main>'; layout_end();
