<?php
require_once __DIR__.'/lib/db.php';
upl_admin_required();
$db=upl_db();
if ($_SERVER['REQUEST_METHOD']==='POST') { upl_check_csrf(); $action=$_POST['action']??''; $id=(int)($_POST['id']??0);
 if(in_array($action,['approve_player','reject_player','delete_player'],true)){ $map=['approve_player'=>'Approved','reject_player'=>'Rejected']; if($action==='delete_player'){$s=$db->prepare('DELETE FROM players WHERE id=?');$s->execute([$id]);}else{$s=$db->prepare('UPDATE players SET status=? WHERE id=?');$s->execute([$map[$action],$id]);} }
 if(in_array($action,['approve_team','reject_team','delete_team'],true)){ if($action==='delete_team'){$s=$db->prepare('DELETE FROM team_interest WHERE id=?');$s->execute([$id]);}else{$s=$db->prepare('UPDATE team_interest SET status=? WHERE id=?');$s->execute([$action==='approve_team'?'Approved':'Rejected',$id]);} }
 if(in_array($action,['delete_news','delete_gallery','delete_fixture','delete_team_record'],true)){ $table=['delete_news'=>'news','delete_gallery'=>'gallery','delete_fixture'=>'fixtures','delete_team_record'=>'teams'][$action]; $db->prepare("DELETE FROM {$table} WHERE id=?")->execute([$id]); }
 if($action==='save_news'){ $title=trim($_POST['title']??'');$body=trim($_POST['body']??''); if($title&&$body)$db->prepare('INSERT INTO news(title,body) VALUES(?,?)')->execute([$title,$body]); }
 if($action==='save_fixture'){ $db->prepare('INSERT INTO fixtures(match_no,team1,team2,match_date,match_time,venue,status,result_text) VALUES(?,?,?,?,?,?,?,?)')->execute([trim($_POST['match_no']??''),trim($_POST['team1']??''),trim($_POST['team2']??''),$_POST['match_date']??null,trim($_POST['match_time']??''),trim($_POST['venue']??''),'Upcoming','']); }
 header('Location: /admin');exit;
}
$players=$db->query('SELECT * FROM players ORDER BY id DESC')->fetchAll();
teams=$db->query('SELECT * FROM team_interest ORDER BY id DESC')->fetchAll();
$fixtures=$db->query('SELECT * FROM fixtures ORDER BY match_date,match_time')->fetchAll();
$news=$db->query('SELECT * FROM news ORDER BY id DESC')->fetchAll();
$gallery=$db->query('SELECT * FROM gallery ORDER BY id DESC')->fetchAll();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UPL Admin</title><link rel="stylesheet" href="/static/style.css"></head><body><main class="wrap"><div class="card"><h1>UPL Admin Panel</h1><p><a class="btn" href="/admin/logout">Logout</a></p></div>
<?php $csrf=upl_csrf(); ?>
<div class="card"><h2>Player Registrations</h2><?php foreach($players as $p):?><div class="card"><b><?=upl_e($p['registration_no'])?> — <?=upl_e($p['full_name'])?></b><p><?=upl_e($p['phone'])?> · <?=upl_e($p['email'])?> · <strong><?=upl_e($p['status'])?></strong></p><form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="id" value="<?=$p['id']?>"><button name="action" value="approve_player" class="btn">Approve</button> <button name="action" value="reject_player" class="btn">Reject</button> <button name="action" value="delete_player" class="btn" onclick="return confirm('Delete this player?')">Delete</button></form></div><?php endforeach;?></div>
<div class="card"><h2>Team Registrations</h2><?php foreach($teams as $t):?><div class="card"><b><?=upl_e($t['interest_no'])?> — <?=upl_e($t['team_name'])?></b><p><?=upl_e($t['contact_name'])?> · <?=upl_e($t['phone'])?> · <strong><?=upl_e($t['status'])?></strong></p><?php if($t['payment_screenshot_url']):?><p><a href="<?=upl_e($t['payment_screenshot_url'])?>" target="_blank">View payment screenshot</a></p><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="id" value="<?=$t['id']?>"><button name="action" value="approve_team" class="btn">Approve</button> <button name="action" value="reject_team" class="btn">Reject</button> <button name="action" value="delete_team" class="btn" onclick="return confirm('Delete this registration?')">Delete</button></form></div><?php endforeach;?></div>
<div class="card"><h2>Fixtures</h2><form method="post" class="grid"><input type="hidden" name="csrf" value="<?=$csrf?>"><input name="match_no" placeholder="Match No"><input name="team1" placeholder="Team 1" required><input name="team2" placeholder="Team 2" required><input name="match_date" type="date" required><input name="match_time" placeholder="Time"><input name="venue" placeholder="Venue"><button name="action" value="save_fixture" class="btn">Add Fixture</button></form><?php foreach($fixtures as $f):?><p><?=upl_e($f['match_no'])?> — <?=upl_e($f['team1'])?> vs <?=upl_e($f['team2'])?> — <?=upl_e($f['match_date'])?> <?=upl_e($f['match_time'])?> <form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="id" value="<?=$f['id']?>"><button name="action" value="delete_fixture" class="btn">Delete</button></form></p><?php endforeach;?></div>
<div class="card"><h2>News</h2><form method="post"><input type="hidden" name="csrf" value="<?=$csrf?>"><input name="title" placeholder="Title" required><textarea name="body" placeholder="News" required></textarea><button name="action" value="save_news" class="btn">Add News</button></form><?php foreach($news as $n):?><p><b><?=upl_e($n['title'])?></b> <form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="id" value="<?=$n['id']?>"><button name="action" value="delete_news" class="btn">Delete</button></form></p><?php endforeach;?></div>
<div class="card"><h2>Gallery</h2><?php foreach($gallery as $g):?><p><?=upl_e($g['title'])?> <form method="post" style="display:inline"><input type="hidden" name="csrf" value="<?=$csrf?>"><input type="hidden" name="id" value="<?=$g['id']?>"><button name="action" value="delete_gallery" class="btn">Delete</button></form></p><?php endforeach;?></div></main></body></html>